remove TeamOrion/ as not needed because remote is orion
causes this error fatal: repository 'https://github.com/TeamOrion/TeamOrion/platform_packages_apps_Bluetooth/' not found
fatal: repository 'https://github.com/TeamOrion/TeamOrion/system_bt/' not found
error: Cannot fetch TeamOrion/platform_packages_apps_Bluetooth
error: Cannot fetch TeamOrion/system_bt
during sync